
server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://158.101.135.115:3306/portfolio?userSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: portfolio
    password: pf1234!
    driver-class-name: com.mysql.cj.jdbc.Driver